services:
  db:
    image: postgres:15
    container_name: insta_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: instaclonedb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      TZ: Europe/Kyiv
    volumes:
      - ./docker-data/postgres:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: insta_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: adminpassword
    command: server /data --console-address ":9001"
    volumes:
      - ./docker-data/minio:/data

  app:
    build: .
    container_name: instagram_backend
    ports:
      - "8080:8080"
    depends_on:
      - db
      - minio
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/instaclonedb
      MINIO_URL: http://minio:9000